name: PHPT Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  phpt-test:
    name: "PHPT Tests"
    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        php-version:
          - 7.1.9
          - 7.1.33
          - 7.2.0
          - 7.2.34
          - 7.3.0
          - 7.3.27
          - 7.4.0
          - 7.4.18
          - 8.0.0
          - 8.0.5
        zts-mode:
          - zts
          - nts
        php-options:
          - "--with-curl"
          - ""
    steps:
      - uses: actions/checkout@v2

      - name: "Set ZTS mode, PHP 8+"
        if: ${{ matrix.zts-mode == 'zts' && startsWith(matrix.php-version, '8.') }}
        run: echo "zts_flag=--enable-zts" >> $GITHUB_ENV
      - name: "Set ZTS mode, PHP 7"
        if: ${{ matrix.zts-mode == 'zts' && startsWith(matrix.php-version, '7.') }}
        run: echo "zts_flag=--enable-maintainer-zts" >> $GITHUB_ENV
      - name: "Set NTS mode"
        if: ${{ matrix.zts-mode == 'nts' }}
        run: echo "zts_flag=" >> $GITHUB_ENV

      - name: "Install PHP ${{ matrix.php-version }} (${{ env.zts_flag}} ${{ matrix.php-options }})"
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get -yq install software-properties-common build-essential autoconf libxml2-dev libsqlite3-dev libcurl4-openssl-dev
          cd /tmp
          FINAL_DOWNLOAD_URL="https://www.php.net/distributions/php-${{ matrix.php-version }}.tar.gz"
          echo "Downloading release from $FINAL_DOWNLOAD_URL ..."
          wget $FINAL_DOWNLOAD_URL
          tar zxf php-${{ matrix.php-version }}.tar.gz
          cd php-${{ matrix.php-version }}
          ./configure --enable-debug --with-openssl ${{ env.zts_flag}} ${{ matrix.php-options }}
          make -j$(nproc)
          sudo make install
          echo '' | pecl install redis
          cd $GITHUB_WORKSPACE
      - name: "Base PHP configuration dump (information)"
        run: php -i
      - name: "Build scoutapm extension"
        run: |
          phpize
          ./configure --enable-scoutapm --enable-scoutapm-dev
          make
      - name: "Run the tests"
        run: |
          php run-tests.php -p `which php` -d zend_extension=`pwd`/modules/scoutapm.so -d extension=redis.so -g "FAIL,XFAIL,BORK,WARN,LEAK,SKIP" --offline --show-diff --set-timeout 120 -q
      - name: "Run the benchmark"
        run: |
          sudo apt update && sudo apt install time
          ./benchmark.sh
          ./benchmark.sh -w
