name: PHPT Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  phpt-test:
    name: "PHPT Tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - 7.1.33
        php-options:
          - "--enable-debug"
    steps:
      - uses: actions/checkout@v2
      - name: "Install PHP"
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get -yq install software-properties-common build-essential autoconf libxml2-dev libsqlite3-dev libcurl4-openssl-dev
          cd /tmp
          FINAL_DOWNLOAD_URL="https://www.php.net/distributions/php-${{ matrix.php-version }}.tar.gz"
          echo "Downloading release from $FINAL_DOWNLOAD_URL ..."
          wget $FINAL_DOWNLOAD_URL
          tar zxf php-${{ matrix.php-version }}.tar.gz
          cd php-${{ matrix.php-version }}
          ./configure ${{ matrix.php-options }}
          make -j$(nproc)
          sudo make install
          cd $GITHUB_WORKSPACE
      - name: "Build scoutapm extension"
        run: |
          phpize
          ./configure --enable-scoutapm --enable-scoutapm-dev
          make
      - name: "Run the tests"
        run: |
          php run-tests.php -p `which php` -d zend_extension=`pwd`/modules/scoutapm.so -g "FAIL,XFAIL,BORK,WARN,LEAK,SKIP" --offline --show-diff --set-timeout 120
