name: PHPT Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  phpt-test:
    name: "PHPT Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
